### ISSUE TITLE
アドインで表示するダイアログをモーダレス表示にした方がよい？

### ISSUE THREAD

**Issue by ISAO-CMS** [COMAS-Ltd/MailYoujin#1]
メールの確認ダイアログが出ていると、他メールを触れない。
送信確認前にメール受信した時に、そっちを見られないのはイマイチ。
送信確認キャンセルしてから、受信したメールみて、また送信確認は手間…

**Comment by momoka-higashiyama** [comment]
モードレス表示に変更するとOutlookにて送信イベントが意図せぬタイミングで実行されてしまうため、本修正は無し。

**Comment by ISAO-CMS** [comment]
意図せぬタイミングとは？
そのタイミングで実行されてしまうことの何が問題？
詳解お願いします。

**Comment by momoka-higashiyama** [comment]
意図せぬタイミングとは、当アドインにおいて送信ボタンが押される前のことです。モードレス表示にすることによってOutlookの送信イベントは非同期で実行されます。
このタイミングで実行されると、メールの確認を行う前に送信されてしまい、誤送信防止用アドインとしての機能を果たせなくなります。
