### ISSUE TITLE
TABキーを押下した際のフォーカスが下から上に上がる

### ISSUE THREAD

**Issue by momoka-higashiyama** [COMAS-Ltd/MailYoujin#4]
TABキーを押下したときの挙動が不自然。上から下に降りるように変更する。

**Comment by momoka-higashiyama** [comment]
アイテムのプロパティの「TabIndex」を設定しました。
Tabキーでアイテム間の移動、上下キーでチェックリストボックス内の移動を行います。また、スペースキーを押下することによってチェックすることができます。

**Comment by ISAO-CMS** [comment]
TABキー押下時のフォーカス遷移を確認しました。
