### ISSUE TITLE
ウィンドウサイズの変更を不可にした方が良い

### ISSUE THREAD

**Issue by momoka-higashiyama** [COMAS-Ltd/MailYoujin#5]
現在、ウィンドウのサイズを変更できるが、各アイテムはサイズが固定されている。ウィンドウサイズも変更できなくてよい

**Comment by momoka-higashiyama** [comment]
フォームのプロパティの「FormBorderStyle」をFixed～にすることで、ウィンドウのサイズを固定。今回はFixed３Dにしました。

**Comment by ISAO-CMS** [comment]
ウィンドウ境界をマウスの操作で拡縮できなくなっていることは確認できました。
以下の点、追加で対応をお願いします。
タイトルバーの、最大化ボタン、最小化ボタンは不要なので表示しないようにしてください。

**Comment by momoka-higashiyama** [comment]
プロパティ―の「MaximizeBox」及び「MinimizeBox」をFalseにすることで最大化最小化ボタンを非表示にします。

**Comment by ISAO-CMS** [comment]
メール、会議案内ともに表示されるウィンドウのサイズが変更できなくなっていることを確認。
