### ISSUE TITLE
会議案内に対応していない

### ISSUE THREAD

**Issue by momoka-higashiyama** [COMAS-Ltd/MailYoujin#6]
会議案内のメールに対応していない

**Comment by momoka-higashiyama** [comment]
[状況]会議案内のメールもメール送信と同じくItemSendイベントのイベントハンドラで実装可能。
しかし、Itemが格納されるオブジェクトが違う(メールはMailItem、会議案内はAppointmentItem)ため、ソースコードの追加が必要。
また、表示する情報も会議案内にあったものにすべき。例えば会議時間や必須参加者、任意参加者等。
以上を含めて対応するか検討。

**Comment by ISAO-CMS** [comment]
別途設計が必要となりますので、時間取って対処しましょう。
イメージは
1．ItemSendイベント受信
2．イベント内容がMailItemであればメール誤送信チェック機能
3．イベント内容がAppointItemであれば会議案内誤送信チェック機能（別画面）
で。

**Comment by momoka-higashiyama** [comment]
出席者、会議場所、日時を追加した画面を作成する。
また、詳しく調査したところ、AppoimtmentItemは予定のイベント、MeetingItemが会議のイベントである。扱う情報はほとんど変わらないので画面は同じものを使用。

**Comment by momoka-higashiyama** [comment]
予定のイベントは送信イベントではなく、保存イベントとなるのでいったん保留

**Comment by momoka-higashiyama** [comment]
予定イベント（AppointmentItem）は対象が自分だけであるため、誤送信防止アドインとしての機能を考慮し対応しない方針で進めます。

**Comment by ISAO-CMS** [comment]
会議案内送信時に送信確認ウィンドウが表示され機能実現できることを確認
