### ISSUE TITLE
アドインの場所を指定したほうが良い

### ISSUE THREAD

**Issue by momoka-higashiyama** [COMAS-Ltd/MailYoujin#7]
インストーラを叩いた箇所がアドインの場所になっているので変更する。
別の場所にコピーしてそちらで実行するバッチもしくはツールを作成。

**Comment by momoka-higashiyama** [comment]
[状況]アドインの保存先
調べたところ、「C:\Users\[User]\AppData\Roaming\Microsoft\AddIns」か「C:\Program Files\Microsoft Office\root\Office16\ADDINS」に保存する。違いは不明なため引き続き調査する。
現在私のPCではOutlookのアドインは後者に保存されている。

**Comment by momoka-higashiyama** [comment]
[状況／追記]アドインの保存先
「C:\Users[User]\AppData\Roaming\Microsoft\AddIns」はExcelアドインの規程のフォルダである。
そのため、Outlook向けVSTOアドインは「C:\Program Files\Microsoft Office\root\Office16\ADDINS」に保存することとする。
ちなみにアドインファイルはOutlookがアクセスできる場所ならどのフォルダに配置してもいい。

**Comment by ISAO-CMS** [comment]
情報提供ありがとうございます。
↑の情報ソースがあればURL等貼り付けておいてもらえますか。

**Comment by momoka-higashiyama** [comment]
Excelアドインの保存先は[ https://srbrnote.work/archives/3145 ] や [ https://penguintan.blog.fc2.com/blog-entry-692.html ]を参照いたしました。
VSTOアドインの配置は[https://docs.microsoft.com/ja-jp/visualstudio/vsto/deploying-an-office-solution?view=vs-2019]にて記載されていますが、配置先について規定がないのと、上記Excelアドインの保存先の説明時にアドインの保存先について言及されており、種類は違いますが同じOffice用アドインであるためアドインファイルはOutlookがアクセスできるフォルダならどこでも良いと判断しました。また、ローカルフォルダ、Cフォルダ等で確認いたしましたが通常通りインストールできました。

**Comment by momoka-higashiyama** [comment]
[状況]配置
バッチで作成予定でしたが、Officeの公式HPにて「Officeソリューションの配置<https://docs.microsoft.com/ja-jp/visualstudio/vsto/deploying-an-office-solution?view=vs-2019>」があるためこちらを参考にWindowsインストーラーを使用してアドインを配置する仕様に変更します。

**Comment by ISAO-CMS** [comment]
インストーラ実行時、
C:\Program Files\Comas\MailYoujin
に格納されることを確認しました。
